@startuml


Class ParkingManager <<Entity>> {
List<ParkingBoy> parkingBoys

+ ParkingBoy findParkingBoy(List<ParkingBoy> parkingBoys)
}

Class ParkingBoy << Entity >> <<Aggregate Root>> {
  List<ParkingLot> parkingLots
  FindParkingLotStrategy findParkingLotStrategy

  + void setParkingLots (ParkingLot[] parkingLots)
  + ParkingLot[] getParkingLots()
}

class ParkingLot << Entity >> <<Aggregate Root>> {
  int capacity
  Map <Ticket, Car> parkedCars

  + Ticket park(Car car)
  + Car take(Ticket ticket)
}

Class Car << Value Object >> {
    PlateNumber plateNumber
}

Class Ticket << Value Object >> {
  + Boolean validate()
}

class FindParkingLotService <<Service>> {
ParkingLot findParkingLot(ParkingBoy parkingBoy)
}

class ParkCarService <<Service>> {
+ Ticket parkCar(ParkingLot parkingLot,Car car)
}

abstract class FindParkingLotStrategy <<Strategy>> {
abstract ParkingLot find(ParkingLot[] parkingLots)
}

Class SortedFindParkingLot{
+ParkingLot find(ParkingLot[] parkingLots)
}

Class SpaceMaxFindParkingLot{
+ParkingLot find(ParkingLot[] parkingLots)
}

FindParkingLotStrategy  <|.. SortedFindParkingLot
FindParkingLotStrategy  <|.. SpaceMaxFindParkingLot
ParkingManager "1" o--> "0..many" ParkingBoy
Ticket "1" *--> "1" Car
ParkingLot "1" o--> "0..many" Ticket
ParkingBoy "1" o--> "0..many" ParkingLot
ParkingBoy "1" o--> "1" FindParkingLotStrategy
FindParkingLotService ..> ParkingBoy
ParkCarService ..> ParkingLot
ParkCarService ..> Car

@enduml